services:
  - name: pcb-detection
    type: web
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y libgl1 libglib2.0-0 libsm6 libxrender1 libxext6 && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
